In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [41]:
title, author, genre, heart, code=[],[],[],[],[]
raw = requests.get('https://www.webtoons.com/en/dailySchedule')
html = BeautifulSoup(raw.text,'html.parser')

for i in range(310,561):    
    title.append(html.select('p.subj')[i].text)   #제목
    author.append(html.select('p.author')[i].text)   #작가
    genre.append(html.select('p.genre')[i].text)    #장르
    if html.select('em.grade_num')[i].text[-1] == 'M':    #하트
        heart.append(int(float(html.select('em.grade_num')[i].text[0:-1])*1000000))
    else :
        heart.append(html.select('em.grade_num')[i].text)
    code.append(re.sub(r'[^0-9]', '', str(html.select('a.daily_card_item')[i].get('href'))[-6:]))  #코드

In [42]:
list_df = pd.DataFrame({'title': title,
                       'code': code,
                       'author': author,
                       'heart': heart,
                       'genre' : genre})
list_df
#맨 처음과 맨 마지막확인함.

,title,code,author,heart,genre
0,Her Bucket List,2564,Yellow sheep / So-p,"709,341",Romance
1,Nevertheless,2647,Jeongseo,"842,812",Romance
2,Freaking Romance,1467,Snailords,19700000,Romance
3,The Wolf & Red Riding Hood,2142,XUANN,3300000,Comedy
4,Annarasumanara,77,Ilkwon Ha,"741,959",Drama
...,...,...,...,...,...
246,City of Walls,505,A.K. Lovelace / Shaun Noel,"19,260",Drama
247,Penguin Loves Mev,86,Penguin,"319,805",Slice of life
248,Cyko-KO,560,Robert Feldman,"8,102",Superhero
249,Jingle Jungle,282,Yongjin Kim,"47,364",Slice of life
250,Nicholalala,418,Nichola Gwon,"182,075",Slice of life

In [43]:
list_df.to_csv('완결미국-제목,작가,장르,하트,코드.csv', index=False)